version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_robinberdier
    volumes:
      - .:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /home/debian/nginx/certs:/etc/nginx/certs:ro
    environment:
      - VIRTUAL_HOST=robinberdier.com,www.robinberdier.com
      - LETSENCRYPT_HOST=robinberdier.com,www.robinberdier.com
      - LETSENCRYPT_EMAIL=contact@robinberdier.com
    networks:
      - webnet

networks:
  webnet:
    external: true